### ISSUE TITLE
Card tapping

### ISSUE THREAD

**Issue by meremarcinko** [vargaspu21/BANG_GameFramework#1]
When I tap on one of the cards multiple times, it seems to close the game occasionally.

When I press the end turn button, im not sure if it actually does anything, then when I tap on one of my cards, more cards seem to appear in my deck. Not sure if that is suppose to happen.

The display looks really good, and it seemed to be working for the most part! :)

**Comment by hujo22** [comment]
That may be one of the bugged cards we had beforehand. We are pretty sure that it is fixed now!

You may be tapping your card while the turn is shifted among the computer players. So when your new turn begins, you draw 2 new cards, and you may think that it's because of the card you selected. If it's not that, it may be a card like wells fargo or stagecoach (that lets you draw cards when played).

Thank you!
